name: Deploy to Azure Web App

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload files to Azure Web App
      env:
        FTP_USERNAME: ${{ secrets.AZURE_FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.AZURE_FTP_PASSWORD }}
        FTP_HOST: ${{ secrets.AZURE_FTP_HOST }}
      run: |
        sudo apt-get install -y lftp
        lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -R ./ /site/wwwroot"
